### ISSUE TITLE
Drop/Keep breaks with multiple dice types

### ISSUE THREAD

**Issue by ThatGuyWhatsMadeofCheese** [Humblemonk/DiceMaiden#103]
**Describe the bug**
When attempting to roll different dice, and keep the highest, keep doesn't work. Same with drop.

**To Reproduce**
!roll 1d8 + 1d10 k1
or
!roll 1d6 + 1d4 d1
**Expected behavior**
Should result in just the highest result, and not the results added together.

**Screenshots**
![image](https://user-images.githubusercontent.com/69303484/90337863-f2d98f00-dfaa-11ea-8343-5cc977f6dd33.png)

**Additional context**
If resolved #15 will be one step closer to done.

**Comment by Humblemonk** [comment]
So this is working as intended. Lets break down one of your example rolls: 1d6+1d8 k1
1d6 = roll one 6 sided die and keep the result
+1d8 = roll one 8 sided die and add it to the result of the d6 result
k1 = keep 1 die from the 8 side die roll. Since there is only one die being rolled here, the bot will ignore the value.

Now if you did the following roll:

!roll 1d6+2d8 k1 

You would get the following result:

[8:29 PM] Humblemonk: !roll 1d6+2d8 k1
[8:29 PM] dice maiden - dogfood: Humblemonk Roll: [1][6, 1] Result: 7

Since two dice were rolled for the d8, the keep command was not ignored and kept the highest die.

Utilizing a math operator will separate the dice pool. The K command will not be able to check between these boundaries.
