### ISSUE TITLE
Error when rolling two single dice

### ISSUE THREAD

**Issue by AmasaDelano** [Humblemonk/DiceMaiden#148]
**Describe the bug**
A roll of two single dice--for instance, `!roll d4+d6`--creates this error:

> Error: + is not between two numbers!

**To Reproduce**
1. Install Dice Maiden on your server
2. Type the command `!roll d4+d6`

**Expected behavior**
I expect Dice Maiden to roll a d4 and a d6 and return the result; for instance: `[4][5] Result: 9`

**Additional context**
The command `!roll 1d4+1d6` works correctly, but not `!roll d4+d6`. Both should work correctly, especially since `!roll d4` and `!roll 1d4` both produce the same output.

**Comment by AmasaDelano** [comment]
I suspect the problem is on line 145 of `dice_maiden_logic.rb`. It looks like the line should be:

`elsif input_queue_peek.match?(/\b\d*[d]\w+/i)# If dice roll`

Where the `\d+` has been changed to `\d*` because a dice roll *may* not have a number in front of it to be a valid dice roll.

I'm not sure if this will screw anything else up, though. Are there automated tests that changes like this should pass? Or should I just submit a pull request, if someone else also thinks this is where the issue is?

**Comment by ThatGuyWhatsMadeofCheese** [comment]
I'm working off of memory here, because I'm too tired to go hunting for specific lines right now, but I _think_ changing it that way might not break anything other than making it throw a different error, but it also wouldn't fix the problem.

`!roll d6` only acts like `!roll 1d6` because there's a line somewhere either in dicemaiden or in dicebag that checks for the former, and replaces it with the latter, before the roll is made. I'm pretty sure that line was written way before you could roll different kinds of dice together, and the regex isn't detecting the second die, the d6 in your example, because it's checking for something at the beginning of the input. (Note, for example, that `!roll d4+1d6` works, while `!roll 1d4+d6` throws the error, so it's specifically the second one that's breaking.

Finding the line that prepends the `1` and updating it to check for multiple types of dice being rolled is probably the way to go.

**Comment by AmasaDelano** [comment]
Ah, I think you're right!

I think I found the code that does this replacement, in lines 68-72 of `dice_maiden.rb`:

```
if @input =~ /^\s*d/
  roll_to_one = @input.lstrip
  roll_to_one.prepend("1")
  @input = roll_to_one
end
```

I'm not familiar with Ruby, but, based on my experience with other languages, I'm guessing there's a regex find and replace function in Ruby? Like:

```
@input = @input.replace(/\D([d]\d+)/, "1" + group)
```

Does this seem like it would work? Or would this screw up something I'm missing?

Thanks! :)

**Comment by ThatGuyWhatsMadeofCheese** [comment]
\D is any non-digit, right? That would probably mess up an alias at some point? But if it requires a space, it would mean that you still couldn't do `!roll d4+d6`. I don't know, I need to stop responding to these when I'm so tired I barely have a brain XD

**Comment by AmasaDelano** [comment]
It seems safest to do this sort of transformation after the dice rolls have already been identified and split up, that is, once `d4` and `d6` etc. have been identified as dice rolls.

Otherwise, if the replacement is made beforehand, as you say, just replacing `dXX` with `1dXX` everywhere could have bizarre consequences. For instance, if a use makes an alias called `hotrod3000`, the regex might turn it into `hotro1d3000`.

We could make it look JUST for dice rolls after "+" signs, which would help with my use case but probably not with others'.

Does anyone else have thoughts about how to resolve this? Thanks! :D

**Comment by Humblemonk** [comment]
A fix for this issue is being rolled out now

**Comment by AmasaDelano** [comment]
Thank you, @Humblemonk! :D
