### ISSUE TITLE
Botch tag for Dicepools

### ISSUE THREAD

**Issue by TashaGrn** [Humblemonk/DiceMaiden#33]
We use the bot for World of Darkness aka Vampire the Masquerade. IN that game 1's subtract from successes (while 10's explode). I would like to be able to add botches into the macro 

ie !10d10 t6 b1 to cause any 1's to subtract from successes. Perhaps this already exists and I missed it.

**Comment by scottlafetra** [comment]
I've made a pull request with this implemented on the humblemonk/Dice-Pool repo. (Although I call them failures instead of botches to be more system agnostic) So, should probably be coming soon. :)

**Comment by Humblemonk** [comment]
Yep! I just merged the the failure roll support.  Breakdown below:

`!roll 5d10 t8 f1` 

f# denotes a failure number that each dice must match or be beneath in order to count against successes. These work as a sort of negative success and are totaled together as described above. 

In the example roll, roll five ten-sided dice and each dice that is 8 or higher is a success and subtract each one. The total may be negative. If the option is given a 0 value, that is the same as not having the option at all thus a normal sum of all dice in the roll is performed instead.

Let me know if that makes sense and would work for "botched rolls",

**Comment by TashaGrn** [comment]
Thanks you are the best :) Also just in time for my saturday Vampire game

Totally works like I expect

Thanks
