### ISSUE TITLE
WoD Botches

### ISSUE THREAD

**Issue by scottlafetra** [Humblemonk/DiceMaiden#52]
Eventually it would be nice to have DM say something if you get a Botch in WoD. (no successes, and at least one "1") Putting this here so I don't forget about it after I take care of more pressing things.

**Comment by bessgeor** [comment]
There is also pretty similar mechanic in ShadowRun called "glitch".
SR uses d6 only with t=5. If you roll 1 on more than the half of dice rolled, it's called a "glitch" (which doesn't cancel out successes rolled). If you roll a glitch and roll no successes, it's called a "critical glitch".
It seems like both WoD botches and SR glitches may be implemented in one feature.

I think the feature may use "low-level" syntax of something like `!roll 5d6 t5 1btGTHalf bCrit` for SR glitches and `!roll 4d10 1bt1 bCritOnly` for WoD botches.
In this syntax,
- `b` stands for botch (because `f` already means failure, which is different because failures are subtracted from the count of successes)
- `bt` stands for botch threshold. Left-side value is the value of dice rolled on which the roll is counted as botch. Right-side value defines threshold (amount of) botches required for the entire roll to be counted as botch. Possible values are number (absolute count of botches) and `GTHalf` (greater than the half of dice rolled). Also, if some system would benefit from this, text values may be complicated to use `GT` as an operator with syntax of `(GT|LT|EQ|GTE|LTE)Half(RU|RD)?` where the first group is comparison operator (`GT` - `>`, `GTE` - `>=`, `EQ` - `=`, `LT` - `<`, `LTE` - `<=`) and the second group is defining rounding (`RU` - rounding up, `RD` - rounding down).
- `bCrit(Only)?` means that botch may crit (use another message, probably) if there are no successes. `Only` modifier means that botch may only crit (e.g. is not printed if there are successes).

Of course, this "low level" syntax may be included into alias expanding for brevity. E.g. WoD becomes `\\1d10 f1 t\\2 1bt1 bCritOnly`. Also, SR alias may be introduced: `/\b\d+SR\b/i, "SR", "\\1d6 t5 1btGTHalf bCrit"`.

Unfortunately, I'm not into Ruby thus may not submit a PR for this in close future.

**Comment by EvRumsey** [comment]
Logic for this in SR4e is on pg 55-56 of the main rulebook. I second the use of `b` as botch is more generally used than glitch.

Rather than automating a result of botch/not botch, it might be safer to add a count of rolls beneath a given value. Since `t#` already outputs number of successes, `b#` outputting count of results below it's threshold would make an easy visual comparison and save the work of counting 1s in the result manually.
