### ISSUE TITLE
Bot has gone offline

### ISSUE THREAD

**Issue by psyjh14** [Humblemonk/DiceMaiden#58]
Bot has gone offline and will not respond to commands.

**Comment by psyjh14** [comment]
![image](https://user-images.githubusercontent.com/26301730/79640143-d4dc5900-8187-11ea-84bd-35c6f7e35fc6.png)

**Comment by Humblemonk** [comment]
This typically happens in the following scenarios:

1. A shard became overloaded and had to restart for various reasons
2. There are very large servers on the shard making it take a long time to cache all the servers from the Discord API payloads. Example logs below:
`! 902 servers haven't been cached yet.
! Servers may be unavailable due to an outage, or your bot is on very large ser
vers that are taking a while to load.`

This typically corrects itself after some time. 

With that said, the bot is limited by the available resources on the hosting provider. Additional shards will help here but deploying anymore today would double the monthly maintenance costs for the bot.  Unfortunately, until more monthly donations come in, this it not an option.

**Comment by Humblemonk** [comment]
If folks would like to support the bots server hosting, please consider becoming a patron! https://patreon.com/dicemaiden
